# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import random

# daftar kata
kata_list = ["apel". "komputer", " kucing", "sekolah", "python"]

# pilih kata random
kata_rahasia = random.choice(kata_list)
tebakan = ["_"] * len(kata_rahasia)

nyawa = 9
huruf ditebak = []

print("Game Tebak Kata")
print("tebak hurufnya yaa!")

while nyawa > 0 and "_" in tebakan:

  print("\nKata:", " ".join(tebakan))
  print("\nNyawa:", nyawa)

  huruf = input("Masukkan huruf: ").lower()

  if huruf in huruf_ditebak:
    print("udah pernah ditebak")
    continue

  huruf_ditebak.append(huruf)

  if huruf in kata_rahasia:
    for i in range(len(kata_rahasia)):
      if tebakan[i] == huruf
    print("benar")
  else:
    nyawa -= 1
    print("salah")

  # hasil akhir
  if "_" not in tebakan:
    print("\nKamu menang! katanya:", kata_rahasia)
  else:
    print("\nGame over. katanya:", kata_rahasia)