# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

**GAME TEBAK ANGKA**
"""

import random

angka_rahasia = random.randint(1,60)
tebakan = 0


while tebakan != angka_rahasia:
  tebakan = int(input("Tebak angka (1-60):  "))

  if tebakan  >=1 and tebakan <=60:
    if tebakan > angka_rahasia:
      print("tebakan terlalu besar")
    elif tebakan < angka_rahasia:
      print("angka terlalu kecil")
    else:
      print("tebakan kamu benar, hebat!")

  else:
    print("masukan angka 1-60")